on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test
jobs:
  llmsframe_embeddings:
    strategy:
      matrix:
        go-version: [1.24.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
#    env:
#      KEY: VALUE
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Docker compose
        run:  docker compose up -d
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -timeout 300s -v --v ./llmsframe/embeddings 